MONGO_DATABASE = {
  USER: '',
  PASSWORD: '',
  NAME: '',
  URI__: ''
}

module.exports = {
  MONGO_DATABASE,
  MONGOURI: `mongodb://${MONGO_DATABASE.USER}:${MONGO_DATABASE.PASSWORD}${MONGO_DATABASE.URI__}/${MONGO_DATABASE.NAME}`
}
